from pathlib import Path
import argparse
import csv
import json
import re
from collections import Counter

import numpy as np
from PIL import Image
from sklearn.metrics import classification_report, confusion_matrix
import tensorflow as tf


PROJECT_ROOT = Path(__file__).resolve().parents[1]

MANIFEST_CSV = PROJECT_ROOT / "data" / "metadata" / "image_manifest_split.csv"
TFLITE_PATH = PROJECT_ROOT / "models" / "gray48_cnn_center_w001_int8" / "gray48_cnn_center_int8.tflite"
DEFAULT_EMBEDDING_EVAL_DIR = PROJECT_ROOT / "models" / "gray48_cnn_center_w001" / "embedding_eval"

_ML_DATA_DIR = PROJECT_ROOT / "data" / "data"
_FACE_DATA_DIR = PROJECT_ROOT.parent / "face" / "data"

if _ML_DATA_DIR.exists():
    DATA_DIR = _ML_DATA_DIR
elif _FACE_DATA_DIR.exists():
    DATA_DIR = _FACE_DATA_DIR
else:
    raise FileNotFoundError(
        f"找不到图片数据目录，检查过:\n  {_ML_DATA_DIR}\n  {_FACE_DATA_DIR}"
    )

IMAGE_SIZE = (48, 48)
CLASS_NAMES = ["person_a", "person_b", "person_c"]
CLASS_TO_INDEX = {name: idx for idx, name in enumerate(CLASS_NAMES)}
IMAGE_SUFFIXES = {".png", ".jpg", ".jpeg"}
EMBEDDING_DIM = 32


def parse_args():
    parser = argparse.ArgumentParser(description="Evaluate INT8 face model and unknown rejection.")
    parser.add_argument(
        "--unknown-dir",
        type=Path,
        default=DATA_DIR / "unknown",
        help="Unknown evaluation image directory. Use a holdout/external folder for a realistic test.",
    )
    parser.add_argument(
        "--centroids-csv",
        type=Path,
        default=DEFAULT_EMBEDDING_EVAL_DIR / "centroids.csv",
        help="Centroid CSV generated by 9_eval_embedding_distance.py.",
    )
    parser.add_argument(
        "--centroids-config",
        type=Path,
        default=DEFAULT_EMBEDDING_EVAL_DIR / "centroids_config.h",
        help="Centroid config header generated by 9_eval_embedding_distance.py.",
    )
    parser.add_argument(
        "--softmax-threshold",
        type=float,
        default=0.99,
        help="Softmax threshold for two-stage deployed evaluation.",
    )
    parser.add_argument(
        "--distance-threshold",
        type=float,
        default=None,
        help="Distance threshold. If omitted, read DISTANCE_THRESHOLD from centroids config.",
    )
    parser.add_argument(
        "--summary-json",
        type=Path,
        default=None,
        help="Optional path for writing a machine-readable evaluation summary.",
    )
    parser.add_argument(
        "--summary-md",
        type=Path,
        default=None,
        help="Optional path for writing a Markdown evaluation summary for the report.",
    )
    return parser.parse_args()


def read_manifest(csv_path):
    rows = []
    with open(csv_path, "r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            row["order_idx"] = int(row["order_idx"])
            row["is_usable"] = int(row["is_usable"])
            rows.append(row)
    return rows


def filter_rows(rows, split_name):
    filtered = []
    for row in rows:
        if row["split"] != split_name:
            continue
        if row["is_usable"] != 1:
            continue
        if row["subject_id"] not in CLASS_TO_INDEX:
            continue
        filtered.append(row)
    return filtered


def print_split_distribution(rows, split_name):
    counter = Counter(row["subject_id"] for row in rows)
    print(f"\n[{split_name}] 样本数量: {len(rows)}")
    for class_name in CLASS_NAMES:
        print(f"  {class_name}: {counter[class_name]}")


def resolve_image_path(filepath_in_manifest):
    parts = Path(filepath_in_manifest).parts
    for i, part in enumerate(parts):
        if part in {"person_a", "person_b", "person_c", "unknown"}:
            return DATA_DIR / Path(*parts[i:])
    return PROJECT_ROOT / filepath_in_manifest


def load_one_image_gray(img_path, image_size):
    img = Image.open(img_path).convert("L")
    img = img.resize(image_size)
    arr = np.asarray(img, dtype=np.float32) / 255.0
    arr = np.expand_dims(arr, axis=-1)   # (48,48) -> (48,48,1)
    return arr


def build_numpy_dataset(rows, image_size):
    x_list = []
    y_list = []

    for row in rows:
        img_path = resolve_image_path(row["filepath"])
        img_array = load_one_image_gray(img_path, image_size)

        label = CLASS_TO_INDEX[row["subject_id"]]
        x_list.append(img_array)
        y_list.append(label)

    x = np.array(x_list, dtype=np.float32)
    y = np.array(y_list, dtype=np.int64)
    return x, y


def load_unknown_images(image_size, unknown_dir):
    if not unknown_dir.exists():
        raise FileNotFoundError(f"Unknown 目录不存在: {unknown_dir}")

    image_files = sorted(
        p for p in unknown_dir.iterdir()
        if p.is_file() and p.suffix.lower() in IMAGE_SUFFIXES
    )
    if not image_files:
        raise ValueError(f"Unknown 目录为空: {unknown_dir}")

    x = np.array([load_one_image_gray(p, image_size) for p in image_files], dtype=np.float32)
    return x, image_files


def print_unknown_rejection(known_probs, unknown_probs):
    known_max = np.max(known_probs, axis=1)
    unknown_max = np.max(unknown_probs, axis=1)
    rows = []

    print("\nUnknown 拒识评估（规则: max_softmax >= threshold 才接受）:")
    print(f"{'threshold':>10} {'known_accept':>16} {'unknown_reject':>18} {'unknown_false_accept':>22}")

    for threshold in [0.95, 0.98, 0.99, 0.995, 0.999]:
        known_accept = int(np.sum(known_max >= threshold))
        unknown_false_accept = int(np.sum(unknown_max >= threshold))
        unknown_reject = len(unknown_max) - unknown_false_accept
        rows.append({
            "threshold": threshold,
            "known_accept": known_accept,
            "known_total": int(len(known_max)),
            "unknown_reject": unknown_reject,
            "unknown_false_accept": unknown_false_accept,
            "unknown_total": int(len(unknown_max)),
        })

        print(
            f"{threshold:>10.3f} "
            f"{known_accept:>7}/{len(known_max):<8} "
            f"{unknown_reject:>8}/{len(unknown_max):<9} "
            f"{unknown_false_accept:>10}/{len(unknown_max):<10}"
        )
    return rows


def load_centroids(centroids_csv):
    centroids = np.zeros((len(CLASS_NAMES), EMBEDDING_DIM), dtype=np.float32)
    with open(centroids_csv, "r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            class_name = row["class_name"]
            if class_name not in CLASS_TO_INDEX:
                continue
            idx = CLASS_TO_INDEX[class_name]
            centroids[idx] = np.array(
                [float(row[f"dim_{i}"]) for i in range(EMBEDDING_DIM)],
                dtype=np.float32,
            )
    return centroids


def load_distance_threshold(args):
    if args.distance_threshold is not None:
        return args.distance_threshold
    if args.centroids_config.exists():
        text = args.centroids_config.read_text(encoding="utf-8")
        match = re.search(r"#define\s+DISTANCE_THRESHOLD\s+([0-9.eE+-]+)f", text)
        if match:
            return float(match.group(1))
    return 2.0


def compute_min_distances(embeddings, centroids):
    diff = embeddings[:, np.newaxis, :] - centroids[np.newaxis, :, :]
    dist_sq = np.sum(diff * diff, axis=2)
    min_dist_sq = np.min(dist_sq, axis=1)
    nearest = np.argmin(dist_sq, axis=1)
    return min_dist_sq, nearest


def print_two_stage_rejection(known_probs, known_embeddings,
                              unknown_probs, unknown_embeddings,
                              centroids, softmax_threshold, distance_threshold):
    if known_embeddings is None or unknown_embeddings is None:
        print("\n当前 TFLite 模型只有 softmax 输出，跳过二阶段 INT8 评估。")
        return None

    distance_threshold_sq = distance_threshold * distance_threshold
    known_max = np.max(known_probs, axis=1)
    unknown_max = np.max(unknown_probs, axis=1)
    known_pred = np.argmax(known_probs, axis=1)
    unknown_pred = np.argmax(unknown_probs, axis=1)

    known_min_dist_sq, known_nearest = compute_min_distances(known_embeddings, centroids)
    unknown_min_dist_sq, unknown_nearest = compute_min_distances(unknown_embeddings, centroids)

    known_accept = (
        (known_max >= softmax_threshold) &
        (known_min_dist_sq <= distance_threshold_sq) &
        (known_pred == known_nearest)
    )
    unknown_accept = (
        (unknown_max >= softmax_threshold) &
        (unknown_min_dist_sq <= distance_threshold_sq) &
        (unknown_pred == unknown_nearest)
    )

    print("\nTwo-stage INT8 拒识评估:")
    print(f"  softmax_threshold: {softmax_threshold:.6f}")
    print(f"  distance_threshold: {distance_threshold:.6f}")
    print(f"  distance_threshold_sq: {distance_threshold_sq:.6f}")
    print(f"  known_accept: {int(np.sum(known_accept))}/{len(known_accept)}")
    print(f"  unknown_reject: {len(unknown_accept) - int(np.sum(unknown_accept))}/{len(unknown_accept)}")
    print(f"  unknown_false_accept: {int(np.sum(unknown_accept))}/{len(unknown_accept)}")
    print(f"  known mean min_dist: {float(np.mean(np.sqrt(known_min_dist_sq))):.4f}")
    print(f"  unknown mean min_dist: {float(np.mean(np.sqrt(unknown_min_dist_sq))):.4f}")
    return {
        "softmax_threshold": float(softmax_threshold),
        "distance_threshold": float(distance_threshold),
        "distance_threshold_sq": float(distance_threshold_sq),
        "known_accept": int(np.sum(known_accept)),
        "known_total": int(len(known_accept)),
        "unknown_reject": int(len(unknown_accept) - np.sum(unknown_accept)),
        "unknown_false_accept": int(np.sum(unknown_accept)),
        "unknown_total": int(len(unknown_accept)),
        "known_mean_min_dist": float(np.mean(np.sqrt(known_min_dist_sq))),
        "unknown_mean_min_dist": float(np.mean(np.sqrt(unknown_min_dist_sq))),
    }



# 跑 TFLite INT8 推理

def run_tflite_inference(x_data, tflite_path):
    interpreter = tf.lite.Interpreter(model_path=str(tflite_path))
    interpreter.allocate_tensors()

    input_details = interpreter.get_input_details()[0]
    output_details = interpreter.get_output_details()

    input_scale, input_zero_point = input_details["quantization"]

    print("\nTFLite 输入信息:")
    print("  shape:", input_details["shape"])
    print("  dtype:", input_details["dtype"])
    print("  quantization:", input_details["quantization"])

    print("\nTFLite 输出信息:")
    softmax_output = None
    embedding_output = None
    for i, details in enumerate(output_details):
        print(f"  output[{i}] shape:", details["shape"])
        print(f"  output[{i}] dtype:", details["dtype"])
        print(f"  output[{i}] quantization:", details["quantization"])
        last_dim = int(details["shape"][-1])
        if last_dim == len(CLASS_NAMES):
            softmax_output = details
        elif last_dim == EMBEDDING_DIM:
            embedding_output = details

    if softmax_output is None:
        raise ValueError("TFLite 模型没有找到 shape 最后一维为 3 的 softmax 输出")

    y_pred = []
    y_prob_dequant = []
    embeddings_dequant = []

    for i in range(len(x_data)):
        x = x_data[i:i+1]   # shape: (1,48,48,1)

        # float32 -> int8
        x_q = np.round(x / input_scale + input_zero_point).astype(np.int8)

        interpreter.set_tensor(input_details["index"], x_q)
        interpreter.invoke()

        output_q = interpreter.get_tensor(softmax_output["index"])   # int8
        output_scale, output_zero_point = softmax_output["quantization"]
        output_f = (output_q.astype(np.float32) - output_zero_point) * output_scale

        pred = int(np.argmax(output_f[0]))
        y_pred.append(pred)
        y_prob_dequant.append(output_f[0])

        if embedding_output is not None:
            emb_q = interpreter.get_tensor(embedding_output["index"])
            emb_scale, emb_zero_point = embedding_output["quantization"]
            emb_f = (emb_q.astype(np.float32) - emb_zero_point) * emb_scale
            embeddings_dequant.append(emb_f[0])

    y_pred = np.array(y_pred, dtype=np.int64)
    y_prob_dequant = np.array(y_prob_dequant, dtype=np.float32)
    embeddings_dequant = (
        np.array(embeddings_dequant, dtype=np.float32)
        if embedding_output is not None else None
    )

    return y_pred, y_prob_dequant, embeddings_dequant


def write_summary_files(args, summary):
    if args.summary_json:
        args.summary_json.parent.mkdir(parents=True, exist_ok=True)
        args.summary_json.write_text(
            json.dumps(summary, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        print(f"\n写入 JSON 摘要: {args.summary_json}")

    if args.summary_md:
        args.summary_md.parent.mkdir(parents=True, exist_ok=True)
        softmax_rows = summary["softmax_threshold_sweep"]
        two_stage = summary.get("two_stage")

        lines = [
            "# INT8 Deployment Evaluation Summary",
            "",
            f"- TFLite model: `{summary['tflite_path']}`",
            f"- Data directory: `{summary['data_dir']}`",
            f"- Unknown directory: `{summary['unknown_dir']}`",
            f"- Test samples: {summary['test_total']}",
            f"- Unknown samples: {summary['unknown_total']}",
            f"- INT8 closed-set accuracy: {summary['int8_test_acc']:.4f}",
            "",
            "## Softmax Threshold Sweep",
            "",
            "| Threshold | Known accept | Unknown reject | Unknown false accept |",
            "|---:|---:|---:|---:|",
        ]
        for row in softmax_rows:
            lines.append(
                f"| {row['threshold']:.3f} | "
                f"{row['known_accept']}/{row['known_total']} | "
                f"{row['unknown_reject']}/{row['unknown_total']} | "
                f"{row['unknown_false_accept']}/{row['unknown_total']} |"
            )

        if two_stage:
            lines.extend([
                "",
                "## Two-Stage Rejection",
                "",
                "| Metric | Value |",
                "|---|---:|",
                f"| Softmax threshold | {two_stage['softmax_threshold']:.6f} |",
                f"| Distance threshold | {two_stage['distance_threshold']:.6f} |",
                f"| Known accept | {two_stage['known_accept']}/{two_stage['known_total']} |",
                f"| Unknown reject | {two_stage['unknown_reject']}/{two_stage['unknown_total']} |",
                f"| Unknown false accept | {two_stage['unknown_false_accept']}/{two_stage['unknown_total']} |",
                f"| Known mean min distance | {two_stage['known_mean_min_dist']:.4f} |",
                f"| Unknown mean min distance | {two_stage['unknown_mean_min_dist']:.4f} |",
            ])

        args.summary_md.parent.mkdir(parents=True, exist_ok=True)
        args.summary_md.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"写入 Markdown 摘要: {args.summary_md}")

def main():
    args = parse_args()

    print("读取 manifest ...")
    rows = read_manifest(MANIFEST_CSV)
    print(f"数据目录: {DATA_DIR}")
    print(f"Unknown 评估目录: {args.unknown_dir}")

    test_rows = filter_rows(rows, "test")
    print_split_distribution(test_rows, "test")

    print("\n加载测试集图片 ...")
    x_test, y_test = build_numpy_dataset(test_rows, IMAGE_SIZE)

    print("\n数据形状:")
    print("x_test:", x_test.shape)
    print("y_test:", y_test.shape)

    print(f"\n加载 TFLite 模型: {TFLITE_PATH}")
    y_pred, y_prob, known_embeddings = run_tflite_inference(x_test, TFLITE_PATH)

    test_acc = float(np.mean(y_pred == y_test))
    print(f"\nINT8 TFLite test_acc = {test_acc:.4f}")

    print("\n测试集分类报告:")
    print(classification_report(
        y_test,
        y_pred,
        target_names=CLASS_NAMES,
        digits=4,
        zero_division=0
    ))

    print("\n测试集混淆矩阵:")
    print(confusion_matrix(y_test, y_pred))

    print("\n加载 unknown 图片 ...")
    x_unknown, unknown_files = load_unknown_images(IMAGE_SIZE, args.unknown_dir)
    print(f"unknown: {len(unknown_files)} 张")
    _, unknown_prob, unknown_embeddings = run_tflite_inference(x_unknown, TFLITE_PATH)
    softmax_rows = print_unknown_rejection(y_prob, unknown_prob)
    two_stage_summary = None

    if args.centroids_csv.exists():
        centroids = load_centroids(args.centroids_csv)
        distance_threshold = load_distance_threshold(args)
        two_stage_summary = print_two_stage_rejection(
            y_prob, known_embeddings,
            unknown_prob, unknown_embeddings,
            centroids,
            args.softmax_threshold,
            distance_threshold,
        )
    else:
        print(f"\n找不到 centroids CSV，跳过二阶段评估: {args.centroids_csv}")

    summary = {
        "tflite_path": str(TFLITE_PATH),
        "data_dir": str(DATA_DIR),
        "unknown_dir": str(args.unknown_dir),
        "test_total": int(len(y_test)),
        "unknown_total": int(len(unknown_files)),
        "int8_test_acc": test_acc,
        "confusion_matrix": confusion_matrix(y_test, y_pred).tolist(),
        "softmax_threshold_sweep": softmax_rows,
        "two_stage": two_stage_summary,
    }
    write_summary_files(args, summary)


if __name__ == "__main__":
    main()
